//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta? wygenerowany przez narz?dzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog? spowodowa? nieprawid?owe zachowanie i zostan? utracone, je?li
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Best_Vayne.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagaj?ca zdefiniowania typu do wyszukiwania zlokalizowanych ci?gów itd.
    /// </summary>
    // Ta klasa zosta?a automatycznie wygenerowana za pomoc? klasy StronglyTypedResourceBuilder
    // przez narz?dzie, takie jak ResGen lub Visual Studio.
    // Aby doda? lub usun?? cz?onka, edytuj plik .ResX, a nast?pnie ponownie uruchom ResGen
    // z opcj? /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wyst?pienie ResourceManager u?ywane przez t? klas?.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Best_Vayne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Zast?puje w?a?ciwo?? CurrentUICulture bie??cego w?tku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomoc? tej klasy zasobów wymagaj?cej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
